security:
  user:
    name: user
    password: pass

spring:
  boot:
    admin:
      url: http://localhost:8080/springBootAdmin
      #These two are needed so that the client
      username: ${security.user.name}
      #can register at the protected server api
      password: ${security.user.password}
      client:
        metadata:
          #These two are needed so that the server
          user.name: ${security.user.name}
          #can access the proteceted client endpoints
          user.password: ${security.user.password}
  application:
    name: SpringBootClient1
management:
  security:
    enabled: false
server:
  port: 8081