security:
  user:
    name: user
    password: pass

spring:
  boot:
    admin:
      url: http://192.168.1.2:8080
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api
      client:
        metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the proteceted client endpoints
  application:
    name: SpringBootClient1
management:
  security:
    enabled: false
server:
  port: 8081